### ISSUE TITLE
输入指令备份后服务端直接崩溃

### ISSUE THREAD

**Issue by HereXianggeGe** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#28]
### Bug description / Bug描述

服务端的命令行输入qb make 1后直接显示三个维度的世界都save了，但是没有显示“备份完成”，而是直接崩溃了，崩溃日志附在下面。
这个服务器存档大小为10G左右，猜测可能是存档过大？

服务器：简幻欢租的，配置：i7 14700k 8G内存25G硬盘

### Steps to reproduce / 复现步骤

1.开服
2.终端输入qb make 1 （此时玩家未进入世界）（二次测试的时候有一名玩家进入世界，但是也崩了）
3.崩溃了

### Expected behavior / 预期行为

正常备份，显示“备份完成”

### Actual behavior / 实际情况

命令行输出：然后崩溃
ThreadedAnvilChunkStorage (world):All chunks are saved
ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
ThreadedAnvilChunkStorage(DIM1): All chunks are saved
ThreadedAnvilChunkStorage: All dimensions are saved

### Relevant logs / 相关日志

https://pastebin.com/psQdz6xh

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

1.2.0

### Other information / 其他信息

我看见1.2.0版本不再维护的通知，但是我无法使用2.0.2来备份（我用我的电脑开服1.20.1也试过，提示无法备份，信息是null），故只能使用1.2.0。希望作者可以在v2修复这个问题，同时烦请解决1.20.1无法备份的问题，感谢！

*我知道需要提交最新版本出现的错误，但是我无法使用最新版本。如果这篇issue违反了大大的规则直接无视或close即可，再次感谢

### Check list

- [x] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
是存档太大这个原因，得开个线程去备份
