### ISSUE TITLE
/qb back 回档时崩溃, 结束进程后重进游戏存档消失

### ISSUE THREAD

**Issue by EiEddie** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#29]
### Bug description / Bug描述

使用 `/qb back` 回档后游戏卡在 "restore backup" 界面十几分钟之久. 结束java进程后重进游戏, 存档消失. 游戏的存档文件夹内仍然有此存档, 但大小不到 1Mb.

当我把 `versions\1.19.4-fabric_0.15.11\QuickBackupMulti\[My World Name]` 文件夹下的 `2024-05-26-225446` (初始化备份时的备份名) 拷贝到游戏存档文件夹下并进入世界后, 发现此世界不是我第一次备份时的世界, 而是我存档列表中的另一世界. 

怀疑初次创建备份时, mod创建的是另一个存档的备份. 我不是很能确定这段时间有没有更改过存档文件夹的名字.

### Steps to reproduce / 复现步骤

在创建了三个备份后:
- "2024-05-26-225446" (这是初次创建的备份)
- "slime farm done"
- "ready to the end"

只需使用回档命令
```
/qb back "ready to the end"
```

### Expected behavior / 预期行为

正常回档

### Actual behavior / 实际情况

卡在 "restore backup" 界面

### Relevant logs / 相关日志

[2024-06-02-3.log.gz](https://github.com/user-attachments/files/15524619/2024-06-02-3.log.gz)
[2024-06-02-2.log.gz](https://github.com/user-attachments/files/15524623/2024-06-02-2.log.gz)

### Minecraft version / Minecraft版本

1.19.4

### Mod version / Mod版本

2.0.2

### Other information / 其他信息

有可能更改了存档文件夹中文件夹的名字

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
用dev版本试试

**Comment by henryyuyhy** [comment]
在昨天的v2.0.5版本中有同样情况，目前暂时没有关闭minecraft进程，在文件资源管理器中发现存档内文件一直在变化
版本：1.20.1
