### ISSUE TITLE
删除槽位后回档时末地/地狱消失

### ISSUE THREAD

**Issue by Roy-QQB-Huang** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#32]
### Bug description / Bug描述

删除槽位后回档时末地/地狱消失

### Steps to reproduce / 复现步骤

/qb make 1
末地/地狱 里进行方块放置/破坏
/qb make 2
/qb delete 1
/qb back 2

### Expected behavior / 预期行为

地图完整地回档

### Actual behavior / 实际情况

1./qb make 1
2.末地/地狱 里进行方块放置/破坏
3./qb make 2
在第二步时更改地狱，则地狱消失
在第二步时更改末地，则末地消失
期间还引起了两次崩溃，log如下（不知是否有关...）

### Relevant logs / 相关日志

[crash-2024-06-12_12.51.00-server.txt](https://github.com/user-attachments/files/15798583/crash-2024-06-12_12.51.00-server.txt)
[crash-2024-06-12_12.58.03-server.txt](https://github.com/user-attachments/files/15798584/crash-2024-06-12_12.58.03-server.txt)
[2024-06-12-1.log](https://github.com/user-attachments/files/15798581/2024-06-12-1.log)
[2024-06-12-2.log](https://github.com/user-attachments/files/15798582/2024-06-12-2.log)

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

QuickBackupMulti-Fabric v2.0.5

### Other information / 其他信息

使用server端运行测试
可能和[#23](https://github.com/SkyDynamic/QuickBackupM-Fabric/issues/23)情况类似？

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by GrapeSkin2191** [comment]
应该和我的 #23 相同
fix when?
