### ISSUE TITLE
qb make后提示No server chosen

### ISSUE THREAD

**Issue by HereXianggeGe** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#36]
### Bug description / Bug描述

备份无法制作，提示错误：
No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: no further information}}]}. Waiting for 30000 ms before timing out

配置：i7-12700H 16G内存 RTX3060
服务端启动参数：
java -Xmx8G -jar fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar

### Steps to reproduce / 复现步骤

1.开服
2.输入qb make 1
3.命令行提示报错，\QuickBackupMulti文件夹内没有备份的文件

如果有玩家在服务器内，该玩家会在输入备份指令后过一段时间连接超时，但也可以再次连接到服务器

### Actual behavior / 实际情况

[04:40:09] [Server thread/INFO]: Make Backup thread started...
[04:40:09] [Server thread/INFO]: No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: no further information}}]}. Waiting for 30000 ms before timing out
[04:40:39] [Server thread/INFO]: An unexpected error occurred trying to execute that command
[04:40:39] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 29972ms or 599 ticks behind
[04:40:39] [Server thread/INFO]: HereXianggeGe lost connection: Disconnected
[04:40:39] [Server thread/INFO]: HereXianggeGe left the game

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.0.5

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by HereXianggeGe** [comment]
已按照模组：
        - appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- ash_api 3.0.2+1.20.1
	- bookshelf 20.1.10
	- carpet 1.4.112+v230608
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- damagenumbers 1.2.0-fabric
	- essential_commands 0.35.0-mc1.20.1
	   |-- ec-core 1.3.0-mc1.20.1
	   |    |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |    |-- placeholder-api 2.1.1+1.20
	   |    \-- playerabilitylib 1.8.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- org_yaml_snakeyaml 2.0
	   |-- placeholder-api 2.1.1+1.20
	   \-- playerabilitylib 1.8.0
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- farmersdelight 1.20.1-1.4.3
	- flourish 3.0.0+1.20.1
	- forgeconfigapiport 8.0.0
	- ftblibrary 2001.2.1
	- ftbultimine 2001.1.4
	- gca 2.7.0-1.20.1
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- htm 1.1.9
	   |-- common-protection-api 1.0.0
	   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	        \-- packet_tweaker 0.3.1+23w06a
	- ibeeditor 2.2.8
	- java 17
	- lithium 0.11.2
	- minecraft 1.20.1
	- minecraftbluearchivehalo 1.20.1-1.0.20.0
	- packetfixer 1.3.2
	- puzzleslib 8.1.18
	   \-- puzzlesaccessapi 8.0.7
	- quickbackupmulti 2.0.5
	   |-- com_h2database_h2 2.2.224
	   |-- de_bwaldvogel_mongo-java-server 1.45.0
	   |-- de_bwaldvogel_mongo-java-server-core 1.45.0
	   |-- de_bwaldvogel_mongo-java-server-h2-backend 1.45.0
	   |-- dev_morphia_morphia_morphia-core 2.3.9
	   |-- org_mongodb_bson 4.11.1
	   |-- org_mongodb_mongodb-driver-core 4.11.1
	   |-- org_mongodb_mongodb-driver-sync 4.11.1
	   \-- org_quartz-scheduler_quartz 2.3.2
	- rei_custom_command 2.2.0
	- roughlyenoughitems 12.1.725
	   \-- error_notifier 1.0.9
	- server-hats 0.16
	- servux 0.1.0
	- simpletextoverlay 1.20.1-5.2.1.3-FABRIC
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   \-- spectrelib 0.13.15+1.20.1
	        |-- com_electronwill_night-config_core 3.6.5
	        \-- com_electronwill_night-config_toml 3.6.5
	- tumbleweed 0.5.5
	- worldedit 7.2.15+6463-5ca4dff
	- worldtools 1.2.4
	- yuushya 2.1.1

**Comment by SkyDynamic** [comment]
没开useInternalDatabase
