### ISSUE TITLE
重进世界崩溃

### ISSUE THREAD

**Issue by esuity** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#41]
### Bug description / Bug描述

退出一个世界再进入另一个会崩溃

### Steps to reproduce / 复现步骤

1.进入一个世界
2.退出
3.进入另一个世界

### Expected behavior / 预期行为

别崩溃(｀・ω・´)

### Actual behavior / 实际情况

崩溃辣(｀・ω・´)

### Relevant logs / 相关日志

[crash-2024-07-25_12.56.18-server.txt](https://github.com/user-attachments/files/16370689/crash-2024-07-25_12.56.18-server.txt)
![屏幕截图 2024-07-25 125629](https://github.com/user-attachments/assets/ac5522c3-3b4a-49c5-86bf-c4961092c6aa)
[错误报告-2024-7-25_12.56.31.zip](https://github.com/user-attachments/files/16370693/-2024-7-25_12.56.31.zip)
[2024-07-25-3.log.gz](https://github.com/user-attachments/files/16370696/2024-07-25-3.log.gz)

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.1.0

### Other information / 其他信息

装了好多好多mod。值得注意的是启动器的报告页面出现mongo单词，但是我的李芒果空岛mod早就卸了啊

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by henryyuyhy** [comment]
与你遇到了完全相同的问题
错误日志如下
[spoiler]游戏核心：1.20.1-机械动力
启动内存：4096 MB
操作系统：Microsoft Windows 10 家庭中文版 x64
————————————————————
CPU：#011th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 
内存：16094
显卡：#0Intel(R) Iris(R) Xe Graphics 
————————————————————
核心路径：C:\Users\bpyxq_gqnzxay\Desktop\mc\新建文件夹\.minecraft\versions\1.20.1-机械动力
Java信息：C:\Program Files\Java17\bin\javaw.exe (Java17.0.10.0 64 Bit)
BakaXL路径：C:\Users\bpyxq_gqnzxay\Desktop\mc\新建文件夹\BakaXL.exe
————————————————————
错误日志：
---- Minecraft 崩溃报告 ----
// There are four lights!
Time: 2024-07-28 21:51:14
崩溃类型： Exception in server tick loop
org.h2.mvstore.MVStoreException: The file is locked: QuickBackupMulti/QuickBackupMulti.mv [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:137)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	at org.h2.mvstore.MVStore.open(MVStore.java:391)
	at de.bwaldvogel.mongo.backend.h2.H2Backend.openMvStore(H2Backend.java:74)
	at de.bwaldvogel.mongo.backend.h2.H2Backend.<init>(H2Backend.java:61)
	at io.github.skydynamic.increment.storage.lib.database.DataBase.startInternalMongoServer(DataBase.java:89)
	at io.github.skydynamic.increment.storage.lib.database.DataBase.<init>(DataBase.java:55)
	at io.github.skydynamic.quickbackupmulti.QuickBackupMulti.setDataBase(QuickBackupMulti.java:169)
	at net.minecraft.server.MinecraftServer.handler$fgm000$quickbackupmulti$initQuickBackupMultiClient(MinecraftServer.java:12323)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:339)
	at net.minecraft.class_1132.method_3823(class_1132.java:69)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:135)
	... 15 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.10, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2386557600 bytes (2275 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=31.0.101.5186
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 4.27
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 4.27
	Memory slot #3 type: LPDDR4
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 4.27
	Memory slot #4 type: LPDDR4
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 4.27
	Memory slot #5 type: LPDDR4
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 4.27
	Memory slot #6 type: LPDDR4
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 4.27
	Memory slot #7 type: LPDDR4
	Virtual memory max (MB): 18526.79
	Virtual memory used (MB): 14908.86
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 287.13
	JVM Flags: 1 total; -Xmx4096M
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.1.12
		bbor: BoundingBoxOutlineReloaded 2.6-1.20.1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carpet: Carpet Mod 1.4.112+v230608
		carpet-extra: Carpet Extra 1.4.115
		carpet-tis-addition: Carpet TIS Addition 1.58.0
			conditional-mixin: conditional mixin 0.6.2
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		configured: Configured 2.2.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create-track-map: Create Track Map 1.4
		custom_hud: CustomHud 3.1.2+1.20.1
		dynamic_fps: Dynamic FPS 3.2.0
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		flighthud: Flight HUD 1.1.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		gammautils: Gamma Utils 1.7.16
		gca: GugleCarpetAddition 2.7.0-1.20.1
		globalpacks: Global Data- & Resourcepacks 1.16.1_fabric
		i18nupdatemod: I18nUpdateMod 3.5.0
		imblocker: IMBlocker 4.0.5
		immediatelyfast: ImmediatelyFast 1.2.5+1.20.2
			net_lenni0451_reflect: Reflect 1.2.1
		indium: Indium 1.0.30+mc1.20.4
		inventoryhud: Inventory HUD + 3.4.18
		itemscroller: Item Scroller 0.20.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 4.0.1
		litematica: Litematica 0.15.3
		litematica_printer: Litematica Printer 7.1.0
		lithium: Lithium 0.11.2
		magiclib-1_20_1: MagicLib for 1.20.1 0.7.398+fe2125a-stable
		malilib: MaLiLib 0.16.3
		masa_gadget_mod-1_20_1: Masa Gadget for 1.20.1 3.2.334+08c8f70-stable
		mcwifipnp: LAN World Plug-n-Play 1.6.9
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		mkb: ModernKeyBinding 1.2.0
		modmenu: Mod Menu 7.2.2
		provihealth: Provi's Health Bars 1.2.4+1.20.1
			lilylib: LilyLib 1.1.3+1.20
		quickbackupmulti: QuickBackupMulti 2.1.0
			com_h2database_h2: h2 2.2.224
			de_bwaldvogel_mongo-java-server: mongo-java-server 1.45.0
			de_bwaldvogel_mongo-java-server-core: mongo-java-server-core 1.45.0
			de_bwaldvogel_mongo-java-server-h2-backend: mongo-java-server-h2-backend 1.45.0
			dev_morphia_morphia_morphia-core: morphia-core 2.3.9
			io_github_skydynamic_incremental-storage-lib: incremental-storage-lib 1.0.4
			org_lz4_lz4-java: lz4-java 1.8.0
			org_mongodb_bson: bson 4.11.1
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.11.1
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.11.1
			org_quartz-scheduler_quartz: quartz 2.3.2
			org_yaml_snakeyaml: snakeyaml 2.0
		quickshulker: Quick Shulker 1.4.0-1.20
			kyrptconfig: Kyrpt Config 1.5.4-1.20
			shulkerutils: shulkerutils 1.0.4-1.19
		railways: Create: Steam 'n' Rails 1.6.4+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		simpleshulkerpreview: Simple Shulker Preview 2.4.0
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		textile_backup: Textile Backup 3.1.2-1.20
			com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
			org_apache_commons_commons-compress: commons-compress 1.22
			org_tukaani_xz: xz 1.9
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		trinkets: Trinkets 3.7.1
		tweakeroo: Tweakeroo 0.17.1
		vmp: Very Many Players 0.2.0+beta.7.102
		voicechat: Simple Voice Chat 1.20.1-2.4.24
		xaerominimapfair: Xaero's Minimap 23.9.4
		xaeroworldmap: Xaero's World Map 1.37.2
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric, CraftingDatapack-v2.2_1.20.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1-机械动力

[/spoiler]

**Comment by SkyDynamic** [comment]
已在最新commit修复
