### ISSUE TITLE
minecraft 1.20.1 无法备份

### ISSUE THREAD

**Issue by Katsuraaa** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#42]
### Bug description / Bug描述

mod版本QuickBackupMulti-mc1.20-v2.1.0。mc版本1.20.1 
Fabric版本 15.2.0.27
游戏正常进入 可以使用/qb setting 等指令
但是输入/qb make 无法创建备份

### Steps to reproduce / 复现步骤

打开存档输入/qb make xxx
无显示内容 输入/qb list提示没有备份

### Expected behavior / 预期行为

应该出现备份中字样

### Actual behavior / 实际情况

没有出现备份中字样。输入qb list 也显示无备份

### Relevant logs / 相关日志

无崩溃情况

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.1.0

### Other information / 其他信息

![image](https://github.com/user-attachments/assets/3ef785c8-b912-4c7e-81d2-9bb613f96c82)
其他mod如下

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
你没给log，就算没崩溃也会有日志
