### ISSUE TITLE
备份时报错

### ISSUE THREAD

**Issue by henryyuyhy** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#43]
### Bug description / Bug描述

进入存档后输入/qb make后立刻输出报错，如图
![image](https://github.com/user-attachments/assets/97426305-fd3d-47bd-8b5e-bc580d1e2c72)

### Steps to reproduce / 复现步骤

/

### Expected behavior / 预期行为

/

### Actual behavior / 实际情况

/

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.1.0

### Other information / 其他信息

安装了很多其他mod，包括另一个备份mod。主要的功能性mod为机械动力以及steam n'rails

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by JIUYINGSHI** [comment]
我也遇到了这个问题，通过排查找出增量备份与Very Many Players这个mod冲突导致的备份失败，具体原因不清楚，你可以检查一下你的mod里有没有这个mod，如果没有也可以跟我一样进行排除查找
