### ISSUE TITLE
1.20.1，模组版本2.1.0退出存档回到主界面再进入任意存档会发生闪退

### ISSUE THREAD

**Issue by CyberT-m** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#45]
### Bug description / Bug描述

1.20.1，模组版本2.1.0退出存档回到主界面再进入任意存档会发生闪退

### Steps to reproduce / 复现步骤

1.点开任意存档
2.退回到主界面
3.再次点开任意存档，加载时即闪退

### Relevant logs / 相关日志

[crash-2024-08-01_03.01.20-server.txt](https://github.com/user-attachments/files/16446244/crash-2024-08-01_03.01.20-server.txt)

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.1.0

### Check list

- [ ] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [ ] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by moxi-duo** [comment]
1.21一样

**Comment by SkyDynamic** [comment]
#41
