### ISSUE TITLE
提示qbm.mv被锁导致同一个游戏实例多开时，进入任意存档会崩溃。

### ISSUE THREAD

**Issue by PAustralis** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#48]
### Bug description / Bug描述

同一个游戏实例多开时，在另一个游戏进程进入任意存档会导致游戏崩溃，Minecraft Crash Report提示“org.h2.mvstore.MVStoreException:The file is locked: .../QuickBackupMulti/qbm.mv"。
![Notepad_4PDvdymgzT](https://github.com/user-attachments/assets/89bfd2c2-8838-4e3e-8aee-d6f7d71fadc3)
[crash-2024-08-06_17.14.05-server.txt](https://github.com/user-attachments/files/16508377/crash-2024-08-06_17.14.05-server.txt)

### Steps to reproduce / 复现步骤

1.打开一个游戏实例
2.打开同一个游戏实例的另一个进程(多开)
3.在第二个打开的游戏进程中进入任意未被第一个游戏进程占用的存档
4.第二个游戏进程崩溃
![javaw_zmm14aiUBQ](https://github.com/user-attachments/assets/adadab95-c4fb-4a7a-962c-3e131c449aee)

### Expected behavior / 预期行为

同一游戏实例下多开的游戏进程可以正常进入存档

### Actual behavior / 实际情况

同一游戏实例下多开的游戏进程在进入存档时崩溃

### Relevant logs / 相关日志

[minecraft-exported-crash-info-2024-08-06T17-21-15.zip](https://github.com/user-attachments/files/16508419/minecraft-exported-crash-info-2024-08-06T17-21-15.zip)

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.0.5 (PS:2.1.0同样存在此问题且有重进存档崩溃问题)

### Other information / 其他信息

装了很多mod，但是感觉跟mod冲突可能没什么关系吧。尝试过复制一个游戏实例，并把该实例目录下的所有文件除了QuickBackupMulti文件夹都使用mklink链接到原本的游戏实例目录，复制的游戏实例可以正常进入存档。
![explorer_Dq4xSWU4fM](https://github.com/user-attachments/assets/acece137-5d11-430e-bee1-24b560fccbb6)

### Check list

- [ ] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [ ] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
#41

**Comment by ksdh2333** [comment]
> #41

在1.21版本中使用v2.1.0+hotfix.1版本依旧有这个问题。

**Comment by SkyDynamic** [comment]
> > #41
> 
> 在1.21版本中使用v2.1.0+hotfix.1版本依旧有这个问题。

请提供复现方式和log（
