### ISSUE TITLE
`/qb list` 备份全部消失

### ISSUE THREAD

**Issue by Immortal-Sty** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#49]
### Bug description / Bug描述

在直接由 **QuickBackupMulti-Fabric v2.0.5** 更新到 **QuickBackupMulti-Fabric v2.1.0+hotfix.1** 后，在游戏中输入 `/qb list` 看不到之前的存档了。

## 版本

- Minecraft：1.19.4
- Fabric：0.16.0
- 其他模组：无

## 步骤

1. 安装 v2.0.5 版本的 qbm；
2. 进入游戏输入 `/qb make 01` 进行备份；
3. 退出游戏升级 qbm 到 v2.1.0+hotfix.1；
4. 重新进入游戏输入 `/qb list` 查看备份。

### Expected behavior / 预期行为

显示备份 `01`。

### Actual behavior / 实际情况

显示不存在备份。

### Relevant logs / 相关日志

- [第一次打开游戏的 log](https://mclo.gs/NrObv6p)
- [第二次打开游戏的 log](https://mclo.gs/itjlPyq)

### Minecraft version / Minecraft版本

1.19.4

### Mod version / Mod版本

2.0.5 -> 2.1.0+hotfix.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by Immortal-Sty** [comment]
我重新把 qbm 版本回退到 2.0.5 后，发现备份又回来了。我现在还是先用 2.0.5 吧，等修好 bug 再更新。

**Comment by SkyDynamic** [comment]
这并不是bug，2.1.0更改了数据库数据存储结构，会让旧版本的存档全部失效

**Comment by Immortal-Sty** [comment]
阿巴阿巴，还真是存储结构问题啊，是那个 `.mv` 文件吗？有法子把旧版本存档更新到新版本吗？要不在更新里加个说明，提示更新后旧存档会丢失？

**Comment by SkyDynamic** [comment]
好

> 阿巴阿巴，还真是存储结构问题啊，是那个 `.mv` 文件吗？有法子把旧版本存档更新到新版本吗？要不在更新里加个说明，提示更新后旧存档会丢失？
