### ISSUE TITLE
多开游戏实例进入不同存档导致崩溃和存档破坏

### ISSUE THREAD

**Issue by ksdh2333** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#50]
### Bug description / Bug描述

仅启用QuickBackupMultiMod时多开实例进入不同的世界，后进入世界的游戏实例崩溃。

### Steps to reproduce / 复现步骤

打开1.21，fabric 0.15.11且仅启用fabric API和本模组的游戏，在当中创建两个存档；
之后启动第一个此版本的实例，进入第一个世界，再启动同一游戏版本另一个实例进入第二个没有被锁定的世界。

### Expected behavior / 预期行为

正常进入第二个世界

### Actual behavior / 实际情况

第二个进入世界的实例崩溃

### Relevant logs / 相关日志

[2024-09-09-3.log.gz](https://github.com/user-attachments/files/16929249/2024-09-09-3.log.gz)
[错误报告-2024-9-9_18.32.22.zip](https://github.com/user-attachments/files/16929251/-2024-9-9_18.32.22.zip)

### Minecraft version / Minecraft版本

1.21

### Mod version / Mod版本

Fabric v2.1.0+hotfix.1

### Other information / 其他信息

创建存档测试前已将所有无关的模组禁用。

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by ksdh2333** [comment]
还有就是这样操作可能会导致两个存档乱掉，就是其中一个存档会变成另一个存档回档后的样子，但是游戏模式和是否作弊还是原来的样子，而真正回档的存档并没有回档成功。

**Comment by SkyDynamic** [comment]
> 还有就是这样操作可能会导致两个存档乱掉，就是其中一个存档会变成另一个存档回档后的样子，但是游戏模式和是否作弊还是原来的样子，而真正回档的存档并没有回档成功。

已确认问题，为`QbmManager.java`的savePath变量始终为第一个打开的存档的问题.
``` Java
public static Path backupDir = Path.of(QbmConstant.pathGetter.getGamePath() + "/QuickBackupMulti/");
    public static Path savePath = Config.TEMP_CONFIG.server.getSavePath(WorldSavePath.ROOT);
    public static IOFileFilter fileFilter = new NotFileFilter(new NameFileFilter(Config.INSTANCE.getIgnoredFiles()));
```

已经在尝试修复
