### ISSUE TITLE
1.21.1服务器配置丢失

### ISSUE THREAD

**Issue by china-xms** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#51]
### Bug description / Bug描述

在1.21.1fabric服务器当中，回档后会丢失许多配置，包括但不限于原版配置（gamerule)、carpet配置（carpet.conf文件）。还可能存在以下的bug（不能确定由本模组导致）：1. 回档后区块文件丢失，区块重新进入未加载的状态（仅出现过一次，未多次发生过） 2. 服务器自动重启出现问题，在回档后执行保存存档关闭服务器之后无法自动开启服务器 3. 回档后导致卡顿
目前无法登陆服务器后台 等可以登陆的时候补一下日志

### Steps to reproduce / 复现步骤

1. 随意更改一些配置
2. 建立一个存档
3. 回档到这个存档
4. 无法正常启动服务器
5. 手动重启

### Expected behavior / 预期行为

一切正常

### Actual behavior / 实际情况

配置丢失
可能的区块丢失
卡顿

### Minecraft version / Minecraft版本

1.21.1

### Mod version / Mod版本

v2.1.0

### Other information / 其他信息

模组列表：
customskinloader floodgate geyser quickbackupmulti ferritecore appleskin carpet-extra carpet-tis-addition fabric-api fabric-carpet litematica servercore servux skinrestorer syncmatica malilib gugle-carpet-addition fabric-language-kotlin

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by china-xms** [comment]
[2024-09-16-1.log.gz](https://github.com/user-attachments/files/17006807/2024-09-16-1.log.gz)
[2024-09-16-2.log.gz](https://github.com/user-attachments/files/17006808/2024-09-16-2.log.gz)
补充一下日志

**Comment by SkyDynamic** [comment]
鉴定为回档失败导致的直接终止回档，现新版本已更改逻辑，会将丢失的跳过
