### ISSUE TITLE
回档后丢失实体

### ISSUE THREAD

**Issue by xhcminecraft** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#57]
### Bug description / Bug描述

我的服务器回档以后村民都没了

### Steps to reproduce / 复现步骤

创建fabric 1.21服务器，安装此模组的2.1.0版本，设置周期性存档，进行回档后，发现所有实体丢失

### Expected behavior / 预期行为

正常回档，还原玩家物品栏和方块实体

### Actual behavior / 实际情况

实体全部消失

### Minecraft version / Minecraft版本

1.21

### Mod version / Mod版本

2.1.0

### Check list

- [ ] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by xhcminecraft** [comment]
虽然我尝试其它备份恢复了实体，但是我认为还有潜在问题

**Comment by xhcminecraft** [comment]
希望作者大大避免模组创建错误备份

**Comment by SkyDynamic** [comment]
不是哥们，你确定最新版本还存在？
现在已经2.2.0+pre-release.2了
