### ISSUE TITLE
/qb make [<name>] [<desc>] 添加描述后无法读取

### ISSUE THREAD

**Issue by ChikaNozomi** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#59]
### Bug description / Bug描述

使用/qb make [name] [desc] 创建备份时，如果在[desc]位置增加描述，创建的备份会命名为[name]+空格+[desc]，且因为带空格，使用back/delete/show指令调取或删除该备份时会提示错误的命令参数，只能在list中查看到且同样无法点击调用

### Steps to reproduce / 复现步骤

1. 创建一个世界
2. 输入”/qb make 001 test“指令
3. 输入”/qb list“查询备份槽位，显示槽位#1名称为”001 test"
4. 点击该槽位或输入“/qb show 001 test”查询详情，提示“错误的命令参数”
5. 使用/qb back和/qb delete同样提示“错误的命令参数”
![2024-10-08_18 55 44](https://github.com/user-attachments/assets/26d15697-ad09-4e74-bb05-1254f1b2b766)

### Expected behavior / 预期行为

输入”/qb make 001 test“指令，期望为创建一个名称为“001”、描述为“test”的备份

### Actual behavior / 实际情况

输入”/qb make 001 test“指令，实际创建了一个名称为“001 test”的备份

### Minecraft version / Minecraft版本

1.21.1

### Mod version / Mod版本

v2.2.0+pre-release.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by ChikaNozomi** [comment]
补充：
1. 多种语言测试结果均一致
2. 若添加引号（如/qb make 001 "test"），则提示Illegal char<"> at index，且不会像旧版本一样把引号部分标黄

**Comment by SkyDynamic** [comment]
messageArgment的问题，谢谢提供！
