### ISSUE TITLE
回档后进入存档，查询备份时提示“试图执行该命令时出现意外错误”

### ISSUE THREAD

**Issue by ChikaNozomi** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#61]
### Bug description / Bug描述

使用/qb back和/qb confirm回档后重新进入存档，使用/qb list、/qb show等指令时提示“试图执行该命令时出现意外错误”

### Steps to reproduce / 复现步骤

1. 创建一个世界
2. 输入/qb make test指令创建备份
3. 待备份创建完成后，输入/qb back test指令，并通过/qb confirm进行确认
4. 10秒后自动退出存档完成回档，重新进入存档

### Expected behavior / 预期行为

操作1. 输入/qb list指令，展示所有备份槽位
操作2. 输入/qb show test，显示该备份详细信息
操作3. 输入/qb delete test，删除该备份
操作4. 输入/qb make new，创建一个新备份

### Actual behavior / 实际情况

1. 操作1/2/3均提示“试图执行该命令时出现意外错误”
2. 操作4无任何响应
3. 退出存档后再次进入存档，执行上述操作，情况相同
4. 退出游戏后重新进入游戏，加载该存档，再执行上述操作，则恢复正常
![2024-10-22_15 23 31](https://github.com/user-attachments/assets/22085e66-2838-48fc-9be4-2b463dee4244)

### Minecraft version / Minecraft版本

1.21.1

### Mod version / Mod版本

v2.2.0

### Other information / 其他信息

1. 仅加载了fabric-api和本mod
2. 经测试v2.2.0+pre-release.3执行相同步骤无此问题

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
估计是数据库没成功重置，我明天有时间看一下，感谢提交

**Comment by SkyDynamic** [comment]
fixed in release 2.2.1
