### ISSUE TITLE
游戏无法多开

### ISSUE THREAD

**Issue by snpdzk** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#66]
### Bug description / Bug描述

正常启动一个客户端后，无法启动第二个并在启动时崩溃

### Steps to reproduce / 复现步骤

启动游戏然后boom

### Relevant logs / 相关日志

https://mclo.gs/CSbMKB5

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.2.0正式版或2.2.0build132

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
此问题为上游特性，内置数据库文件仅能单个存档访问，若多开会直接崩溃，如果需要多开请自行搭建MongoDB服务，本地也可以搭建的，可以去了解一下
