### ISSUE TITLE
无法正常重启

### ISSUE THREAD

**Issue by china-xms** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#68]
### Bug description / Bug描述

1.21.1服务器回档后无法正常重启

### Steps to reproduce / 复现步骤

1.创建一个备份
2.回档
3.无法正常开启服务器
4.服务器后台跳出报错

### Expected behavior / 预期行为

服务器正常开启

### Actual behavior / 实际情况

服务器无法开启并且报错
java.lang.IllegalStateException: state should be: open

### Relevant logs / 相关日志

[2024-11-16-2.log](https://github.com/user-attachments/files/17784753/2024-11-16-2.log)

### Minecraft version / Minecraft版本

1.21.1

### Mod version / Mod版本

v2.2.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
试一下用action内的mod
那个应该没问题

**Comment by china-xms** [comment]
在哪里啊

**Comment by SkyDynamic** [comment]
fixed in release 2.2.1
