### ISSUE TITLE
单人生存存档无法备份

### ISSUE THREAD

**Issue by Realzhazha** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#69]
### Bug description / Bug描述

设置定时备份或者手动备份均有问题

### Steps to reproduce / 复现步骤

使用`/qb make`之后，会提示
```
备份失败，错误原因java.lang.NullPointerException: Cannot invoke "org.quartz.Scheduler.shutdown()" because "io.github.skydynamic.quickbackupmulti.config.Config.TEMP_CONFIG.scheduler" is null
```
使用`/qb setting schedule enable` 会提示 “试图执行该命令时出现意外错误”
![image](https://github.com/user-attachments/assets/e3b120b9-f5ed-4f28-9ffc-3cf976402904)

### Relevant logs / 相关日志

https://mclo.gs/zrgfzz8

### Minecraft version / Minecraft版本

1.20.4

### Mod version / Mod版本

2.2.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
fixed in release 2.2.1
