### ISSUE TITLE
文件锁定导致备份失败

### ISSUE THREAD

**Issue by Realzhazha** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#70]
### Bug description / Bug描述

使用/qb make的时候，显示文件被锁定，进程无法访问

### Steps to reproduce / 复现步骤

使用/qb make的时候，显示
```
备份失败，错误原因java.nio.file.FileSystemException: F:\Minecraft\versions\1.20.4-Fabric 0.16.3\saves\Void Machines\.\session.lock -> F:\Minecraft\versions\1.20.4-Fabric 0.16.3\QuickBackupMulti\Void Machines\2024-11-30-235712\session.lock: 另一个程序已锁定文件的一部分，进程无法访问。
```
![image](https://github.com/user-attachments/assets/b7d401b2-2244-4f2d-a495-0947199a2081)

### Relevant logs / 相关日志

https://mclo.gs/yvdU4Xy

### Minecraft version / Minecraft版本

1.20.4

### Mod version / Mod版本

2.2.1

### Other information / 其他信息

2.2.0版本的时候有时候会有bug有时候可以备份成功，但是只有2.2.1会100%复现提示文件被锁定

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
已在其他issues解释过问题，存在问题重复提交，不给予后续跟踪

**Comment by SkyDynamic** [comment]
你可以尝试往config.json内的IgnoreFile字段添加"session.lock"
