### ISSUE TITLE
最新版本备份时提示文件session.lock被占用无法操作

### ISSUE THREAD

**Issue by abc05277** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#74]
### Bug description / Bug描述

最新版本V2.2.1备份时提示文件session.lock被占用无法操作，但是V2.2.0可以正常备份，回档后会出现功能无法使用的情况。加油哦，我很看好这个mod。
![Image_2957878106618969](https://github.com/user-attachments/assets/cf8dd83c-37eb-4bf3-b091-096e291372e4)

### Steps to reproduce / 复现步骤

V2.2.1直接无法创建备份
V2.2.0可以正常备份，回档后会出现功能无法使用的情况

### Minecraft version / Minecraft版本

1.21.1

### Mod version / Mod版本

V2.2.1、V2.2.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by iceRedtea1145** [comment]
可以尝试往config.json内的IgnoreFile字段添加"session.lock"，但是在1.18.2回档等操作还是会出现 “执行该指令时出现意外错误”
