### ISSUE TITLE
v2.2.1 Failed to start the minecraft server于1.20.1server

### ISSUE THREAD

**Issue by MCTVVTCM** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#75]
### Bug description / Bug描述

.

### Steps to reproduce / 复现步骤

[latest.log](https://github.com/user-attachments/files/18265781/latest.log)

### Expected behavior / 预期行为

.

### Actual behavior / 实际情况

.

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.2.1以上和预览版

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
同#72
